# postgres
#
defaults_development: &defaults_development
  adapter: postgresql
  encoding: unicode
  username: Junir
  password:
  host: localhost

development:
  database: application_dev
  <<: *defaults_development

test:
  database: application_test
  <<: *defaults_development
